apiVersion: apps/v1
kind: Deployment
metadata:
  name: isf-upgrade
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: isf-upgrade-container
        image: docker.io/grafana/grafana:10.4.3
        ports:
        - containerPort: 80
